//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 基于云的Web管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentInfo
    {
        public long Id { get; set; }
        public string Contact { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> SubData { get; set; }
        public Nullable<byte> IsRead { get; set; }
        public Nullable<System.DateTime> ReDate { get; set; }
    }
}
